<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Souradeep" ignored="1" name="Test1" tests="1" failures="1" timestamp="28 Oct 2018 09:03:13 GMT" time="49.887" errors="0">
  <testcase name="loginFaceBook" time="41.72" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at tests.LoginTest.loginFaceBook(LoginTest.java:25)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginFaceBook -->
  <testcase name="testDemoFaceBook" time="0.0" classname="tests.LoginTest">
    <ignored/>
  </testcase> <!-- testDemoFaceBook -->
</testsuite> <!-- Test1 -->
