<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Souradeep" ignored="0" name="Test" tests="3" failures="2" timestamp="23 Sep 2018 12:17:31 GMT" time="53.372" errors="0">
  <testcase name="testDemo" time="0.55" classname="tests.Demo"/>
  <testcase name="testDemoFaceBook" time="0.019" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at tests.LoginTest.testDemoFaceBook(LoginTest.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testDemoFaceBook -->
  <testcase name="loginFaceBook" time="44.732" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at tests.LoginTest.loginFaceBook(LoginTest.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginFaceBook -->
</testsuite> <!-- Test -->
